### ISSUE TITLE
[Feat] 방 입장하기 뷰 구현

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#13]
## 🛠 Issue
- 방 입장하기 뷰 구현

## 📋 To-do
- [ ] 방 입장하기 뷰 UI 구현하기
- [ ] 방 입장하기 뷰 비즈니스 로직 구현하기
- [ ] 마니또 방 UI 구현하기
- [ ] 마니또 방 비즈니스 로직 구현하기
