### ISSUE TITLE
[Feat] 방 만들기 뷰 비즈니스 로직 구체화

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#25]
## 🛠 Issue
- 방 만들기 뷰 비즈니스 로직 구체화

## 📋 To-do
- [ ] EditRoomInfoViewModel에 필요한 Entity 생성하기
- [ ] StubRoomService 생성 및 EditRoomInfoViewModel에 필요한 로직 작업하기
- [ ] EditMissionViewModel에 필요한 Entity 생성하기
- [ ] StubRoomService 생성 및 EditMissionViewModel에에 필요한 로직 작업하기
- [ ] CheckRoomInfoViewModel에 필요한 Entity 생성하기
- [ ] StubRoomService 생성 및 CheckRoomInfoViewModel에에 필요한 로직 작업하기
