### ISSUE TITLE
[Feat] 방 입장하기 뷰 비즈니스 로직 구체화 

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#26]
## 🛠 Issue
- 방 입장하기 뷰 비즈니스 로직 구체화 

## 📋 To-do
- [ ] EnterRoomViewModel에 필요한 Entity 생성
- [ ] StubEnterRoomService 생성 및 EnterRoomViewModel에 필요한 로직 작업하기
- [ ] ManitoRoomViewModel에 필요한 Entity 생성
- [ ] StubEnterRoomService 생성 및 ManitoRoomViewModel에 필요한 로직 작업하기
