### ISSUE TITLE
[Feat] 네트워크 모듈 구현하기 

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#42]
## 🛠 Issue
- 네트워크 모듈 구현하기

## 📋 To-do
- [ ] URLRequestConfigurable 구현하기
- [ ] BaseAPI 구현하기
- [ ] BaseAPI 채택해서 각 서비스 API 구현하기
- [ ] HTTPMethod 파일 구현하기
- [ ] Header 파일 구현하기
- [ ] ParameterEncodable 인터페이스 구현하기
- [ ] URLEncoding, JsonEncoding 구현하기
- [ ] BaseService 구현하기
- [ ] NetworkProvider 구현하기
- [ ] 각 ServiceType 인터페이스와 Stub 수정하기
- [ ] NetworkError 구현하기
