### ISSUE TITLE
[Feat] 매칭 및 결과보기 뷰 UI 수정사항 반영

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#58]
## 🛠 Issue
- 매칭 및 결과보기 뷰 UI 수정사항 반영

## 📋 To-do
- [ ] 매칭 뷰 로티 추가하기
- [ ] 결과보기 뷰 수정사항 반영하기
- [ ] 마니또 매칭 결과보기 뷰 수정사항 반영하기
