### ISSUE TITLE
[QA] QA반영하기

### ISSUE THREAD

**Issue by HELLOHIDI** [manito-project/SantaManito-iOS#90]
## 🛠 Issue
- QA반영하기

## 📋 To-do
- [ ] [방 입장하기] iOS 초대코드 입력 후 에러메시지
- [ ] [방 입장하기] iOS 뒤로 가기 시 홈 화면 이동으로 변경 필요
- [ ] 마니또 캐릭터 아이콘 동일 노출되는 문제 / 날짜와 참여자 좁음
- [ ] [마니또방] iOS 버튼명 수정
- [ ] [방 정보 설정] 디자인 글자 정렬 수정 제안
- [ ] [미션 만들기] iOS 미션 추가 시, 위에 입력한 미션이 똑같이 입력되고 있음
- [ ] [미션 만들기] iOS 1개 미션에 대해 삭제 했으나, 2개가 동시에 삭제되고 있음
